//
// Created by Doruk Tan Atila on 10/26/23.
//

#ifndef MAIN_CPP_PARAMETERS_H
#define MAIN_CPP_PARAMETERS_H

#include "cmath"

const double ELEMENTARY_CHARGE = (1.602 * pow(10,-19));			//C
const double BOLTZMANN_CONSTANT = (1.380649 * pow(10, -23));	//J/K
const double PLANCK_CONSTANT = (4.135667696 * pow(10, -15));	//eV*s
const double PI = 3.14159265358979323846;
const double EULERS_NUMBER = 2.71828182845904523536;
const double ROOM_TEMPERATURE = 300;	//K
const double THERMAL_VOLTAGE_ROOM_TEMPERATURE = (BOLTZMANN_CONSTANT * ROOM_TEMPERATURE) / ELEMENTARY_CHARGE;	//V
const double VACUUM_PERMITTIVITY = (8.8541878128 * pow(10, -12));	//F/m


const int imageW = 1200;
const int imageL = 800;



//Material Constants - From http://www.matprop.ru/
const double ALUMINUM_WORK_FUNCTION = 4.20;	//eV


const double SILICON_BANDGAP = 1.12;	//eV
const double SILICON_ELECTON_AFFINITY = 4.05;	//eV
const double SILICON_EFFECTIVE_DENSITY_OF_STATES_IN_CONDUCTION_BAND = 3.2;	//cm^-3
const double SILICON_EFFECTIVE_DENSITY_OF_STATES_IN_VALANCE_BAND = 1.8;	//cm^-3
const double SILICON_ELECTRON_MOBILITY = 1400;	//cm^2/Vs
const double SILICON_HOLE_MOBILITY = 450;	//cm^2/Vs
const double SILICON_DIELECTRIC_CONSTANT = 11.68;	//unitless

const double GERMANIUM_BANDGAP = 0.661;	//eV
const double GERMANIUM_ELECTON_AFFINITY = 4.0;	//eV
const double GERMANIUM_EFFECTIVE_DENSITY_OF_STATES_IN_CONDUCTION_BAND = 1.0;	//cm^-3
const double GERMANIUM_EFFECTIVE_DENSITY_OF_STATES_IN_VALANCE_BAND = 0.5;	//cm^-3
const double GERMANIUM_ELECTRON_MOBILITY = 3900;	//cm^2/Vs
const double GERMANIUM_HOLE_MOBILITY = 1900;	//cm^2/Vs
const double GERMANIUM_DIELECTRIC_CONSTANT = 16.2;	//unitless

const double GALLIUM_ARSENIDE_BANDGAP = 1.424;	//eV
const double GALLIUM_ARSENIDE_ELECTON_AFFINITY = 4.07;	//eV
const double GALLIUM_ARSENIDE_EFFECTIVE_DENSITY_OF_STATES_IN_CONDUCTION_BAND = 0.047;	//cm^-3
const double GALLIUM_ARSENIDE_EFFECTIVE_DENSITY_OF_STATES_IN_VALANCE_BAND = 0.9;	//cm^-3
const double GALLIUM_ARSENIDE_ELECTRON_MOBILITY = 8500;	//cm^2/Vs
const double GALLIUM_ARSENIDE_HOLE_MOBILITY = 400;	//cm^2/Vs
const double GALLIUM_ARSENIDE_DIELECTRIC_CONSTANT = 12.9;	//unitless




#endif //MAIN_CPP_PARAMETERS_H
